#!/bin/sh

set -e

srcdir="$(dirname "$0")"
cd "$srcdir"

clone_repo_commit() {
    local url="$1"
    local dir="../limine-tools/$2"
    local commit="$3"

    if test -d "$dir/.git"; then
        git -C "$dir" reset --hard
        git -C "$dir" clean -fd
        git -C "$dir" -c advice.detachedHead=false checkout "$commit" || exit 1
    else
        rm -rf "$dir"
        git clone "$url" "$dir"
        git -C "$dir" -c advice.detachedHead=false checkout "$commit" || exit 1
    fi
}

# Создаём директорию limine-tools при необходимости
mkdir -p ../limine-tools

rm -f .deps-obtained

clone_repo_commit https://codeberg.org/OSDev/freestnd-c-hdrs-0bsd.git freestnd-c-hdrs 5e4e9e70278fe89ea328d359a58aff4f4a94b165
clone_repo_commit https://codeberg.org/OSDev/cc-runtime.git cc-runtime dae79833b57a01b9fd3e359ee31def69f5ae899b
clone_repo_commit https://codeberg.org/Limine/limine-protocol.git limine-protocol fedf97facd1c473ee8720f8dfd5a71d03490d928

touch .deps-obtained
echo "
Dependencies obtained successfully.
"